---
deployment:
  tasks:
    - export DEPLOYPATH=/home/o44uty6ifogt/Budget/
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp yarn.lock $DEPLOYPATH
   