---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uq44x878gx66/node/
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp yarn.lock $DEPLOYPATH
   